spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mariadb://localhost:3306/first?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    mybatis:
        #实体类所做包
        type-aliases-package: model
        #mapper.xml所在位置
        mapper-locations: classpath:mappers/*.xml

