spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: dphdglxt
    password: dphdglxt123
    url: jdbc:mariadb://localhost:3306/first?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
mybatis:
  #实体类所做包
  type-aliases-package: learning.model2
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*.xml

